sudo: required

language: cpp
complier:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python3-pip python3-dev build-essential
  - sudo pip3 install --upgrade pip
  - sudo pip3 install meson

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - meson build
  - sudo ninja -C build