sudo: required

language: cpp
complier:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential wget
  - echo -e "\n" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get install g++-7

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7"; fi

script:
  - wget https://github.com/vapoursynth/vapoursynth/archive/R49-RC1.tar.gz
  - tar -xzvf R49-RC1.tar.gz vapoursynth-R49-RC1/include
  - mkdir JincResize/vapoursynth
  - mv vapoursynth-R49-RC1/include/VapourSynth.h JincResize/vapoursynth/VapourSynth.h
  - mv vapoursynth-R49-RC1/include/VSHelper.h JincResize/vapoursynth/VSHelper.h
  - cd JincResize
  - g++ -shared -fPIC -std=c++17 -O2 -march=native -o JincResize.so JincResize.cpp
