name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '.gitmodules'
      - '**/LICENSE'
      - '**.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '.gitmodules'
      - '**/LICENSE'
      - '**.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: configure
        run: |
          wget https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R53.tar.gz
          tar -xzvf R53.tar.gz vapoursynth-R53/include
          mkdir include/vapoursynth
          mv vapoursynth-R53/include/VapourSynth.h include/vapoursynth/VapourSynth.h
          mv vapoursynth-R53/include/VSHelper.h include/vapoursynth/VSHelper.h
          
      - name: build
        run: g++ -shared -fPIC -std=c++17 -O3 -march=native src/JincResize.cpp -o JincResize.so

